name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: install pacakges
        run: yarn

      - name: build
        run: yarn build

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: static
          path: build/

  deploy:
    environment: testnet
    needs: build
    runs-on: ubuntu-latest
    env:
      REACT_APP_CHAIN_ENV: testnet
      REACT_APP_ACCESS_NODE: https://flow-testnet.g.alchemy.com
      REACT_APP_ALCHEMY_API_KEY: ${{ secrets.REACT_APP_ALCHEMY_API_KEY }}
      REACT_APP_WALLET_DISCOVERY: https://fcl-discovery.onflow.org/testnet/authn
      REACT_APP_CONTRACT_NON_FUNGIBLE_TOKEN: 0x631e88ae7f1d7c20
      REACT_APP_CONTRACT_FUNGIBLE_TOKEN: 0x9a0766d93b6608b7
      REACT_APP_CONTRACT_COGITO: 0x441422d5b5a1758b
      REACT_APP_DETAIL_ICON: https://wkdt-pocket-3ghyf7p36445e5ef-1304586669.tcloudbaseapp.com/logo512.png
      REACT_APP_DETAIL_TITLE: "Cogito ergo sum"
      REACT_APP_WEB3_STORAGE_DEFAULT_KEY: ${{ secrets.WEB3STORAGE }}
    steps:
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: static
          path: build
      - name: upload to web3
        uses: web3-storage/add-to-web3@v1.0.0
        with:
          path_to_add: build
          web3_token: ${{ secrets.WEB3STORAGE }}
          web3_api: https://api.web3.storage
          wrap_with_directory: false
